[package]
name = "fastjet-rs"
version = "0.1.0"
edition = "2024"

[profile.profiling]
inherits = "release"
debug = "line-tables-only"

[dependencies]

[profile.release]
codegen-units = 1
lto = "thin"

